version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install Stack
          command: curl -sSL https://get.haskellstack.org/ | sh
      - run:
          name: Run test
          command: stack test
